// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using SDL;

namespace Silk.NET.Input.Sdl
{
    partial class SdlKeyboard
    {
        private static readonly Dictionary<SDL_Scancode, Key> _keyMap = new()
        {
            { SDL_Scancode.SDL_SCANCODE_UNKNOWN, Key.Unknown },
            { SDL_Scancode.SDL_SCANCODE_A, Key.A },
            { SDL_Scancode.SDL_SCANCODE_B, Key.B },
            { SDL_Scancode.SDL_SCANCODE_C, Key.C },
            { SDL_Scancode.SDL_SCANCODE_D, Key.D },
            { SDL_Scancode.SDL_SCANCODE_E, Key.E },
            { SDL_Scancode.SDL_SCANCODE_F, Key.F },
            { SDL_Scancode.SDL_SCANCODE_G, Key.G },
            { SDL_Scancode.SDL_SCANCODE_H, Key.H },
            { SDL_Scancode.SDL_SCANCODE_I, Key.I },
            { SDL_Scancode.SDL_SCANCODE_J, Key.J },
            { SDL_Scancode.SDL_SCANCODE_K, Key.K },
            { SDL_Scancode.SDL_SCANCODE_L, Key.L },
            { SDL_Scancode.SDL_SCANCODE_M, Key.M },
            { SDL_Scancode.SDL_SCANCODE_N, Key.N },
            { SDL_Scancode.SDL_SCANCODE_O, Key.O },
            { SDL_Scancode.SDL_SCANCODE_P, Key.P },
            { SDL_Scancode.SDL_SCANCODE_Q, Key.Q },
            { SDL_Scancode.SDL_SCANCODE_R, Key.R },
            { SDL_Scancode.SDL_SCANCODE_S, Key.S },
            { SDL_Scancode.SDL_SCANCODE_T, Key.T },
            { SDL_Scancode.SDL_SCANCODE_U, Key.U },
            { SDL_Scancode.SDL_SCANCODE_V, Key.V },
            { SDL_Scancode.SDL_SCANCODE_W, Key.W },
            { SDL_Scancode.SDL_SCANCODE_X, Key.X },
            { SDL_Scancode.SDL_SCANCODE_Y, Key.Y },
            { SDL_Scancode.SDL_SCANCODE_Z, Key.Z },
            { SDL_Scancode.SDL_SCANCODE_1, Key.Number1 },
            { SDL_Scancode.SDL_SCANCODE_2, Key.Number2 },
            { SDL_Scancode.SDL_SCANCODE_3, Key.Number3 },
            { SDL_Scancode.SDL_SCANCODE_4, Key.Number4 },
            { SDL_Scancode.SDL_SCANCODE_5, Key.Number5 },
            { SDL_Scancode.SDL_SCANCODE_6, Key.Number6 },
            { SDL_Scancode.SDL_SCANCODE_7, Key.Number7 },
            { SDL_Scancode.SDL_SCANCODE_8, Key.Number8 },
            { SDL_Scancode.SDL_SCANCODE_9, Key.Number9 },
            { SDL_Scancode.SDL_SCANCODE_0, Key.Number0 },
            { SDL_Scancode.SDL_SCANCODE_RETURN, Key.Enter },
            { SDL_Scancode.SDL_SCANCODE_ESCAPE, Key.Escape },
            { SDL_Scancode.SDL_SCANCODE_BACKSPACE, Key.Backspace },
            { SDL_Scancode.SDL_SCANCODE_TAB, Key.Tab },
            { SDL_Scancode.SDL_SCANCODE_SPACE, Key.Space },
            { SDL_Scancode.SDL_SCANCODE_MINUS, Key.Minus },
            { SDL_Scancode.SDL_SCANCODE_EQUALS, Key.Equal },
            { SDL_Scancode.SDL_SCANCODE_LEFTBRACKET, Key.LeftBracket },
            { SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET, Key.RightBracket },
            { SDL_Scancode.SDL_SCANCODE_BACKSLASH, Key.BackSlash },
            //{SDL_Scancode.ScancodeNonushash, /* no mapping */},
            { SDL_Scancode.SDL_SCANCODE_SEMICOLON, Key.Semicolon },
            { SDL_Scancode.SDL_SCANCODE_APOSTROPHE, Key.Apostrophe },
            { SDL_Scancode.SDL_SCANCODE_GRAVE, Key.GraveAccent },
            { SDL_Scancode.SDL_SCANCODE_COMMA, Key.Comma },
            { SDL_Scancode.SDL_SCANCODE_PERIOD, Key.Period },
            { SDL_Scancode.SDL_SCANCODE_SLASH, Key.Slash },
            { SDL_Scancode.SDL_SCANCODE_CAPSLOCK, Key.CapsLock },
            { SDL_Scancode.SDL_SCANCODE_F1, Key.F1 },
            { SDL_Scancode.SDL_SCANCODE_F2, Key.F2 },
            { SDL_Scancode.SDL_SCANCODE_F3, Key.F3 },
            { SDL_Scancode.SDL_SCANCODE_F4, Key.F4 },
            { SDL_Scancode.SDL_SCANCODE_F5, Key.F5 },
            { SDL_Scancode.SDL_SCANCODE_F6, Key.F6 },
            { SDL_Scancode.SDL_SCANCODE_F7, Key.F7 },
            { SDL_Scancode.SDL_SCANCODE_F8, Key.F8 },
            { SDL_Scancode.SDL_SCANCODE_F9, Key.F9 },
            { SDL_Scancode.SDL_SCANCODE_F10, Key.F10 },
            { SDL_Scancode.SDL_SCANCODE_F11, Key.F11 },
            { SDL_Scancode.SDL_SCANCODE_F12, Key.F12 },
            { SDL_Scancode.SDL_SCANCODE_PRINTSCREEN, Key.PrintScreen },
            { SDL_Scancode.SDL_SCANCODE_SCROLLLOCK, Key.ScrollLock },
            { SDL_Scancode.SDL_SCANCODE_PAUSE, Key.Pause },
            { SDL_Scancode.SDL_SCANCODE_INSERT, Key.Insert },
            { SDL_Scancode.SDL_SCANCODE_HOME, Key.Home },
            { SDL_Scancode.SDL_SCANCODE_PAGEUP, Key.PageUp },
            { SDL_Scancode.SDL_SCANCODE_DELETE, Key.Delete },
            { SDL_Scancode.SDL_SCANCODE_END, Key.End },
            { SDL_Scancode.SDL_SCANCODE_PAGEDOWN, Key.PageDown },
            { SDL_Scancode.SDL_SCANCODE_RIGHT, Key.Right },
            { SDL_Scancode.SDL_SCANCODE_LEFT, Key.Left },
            { SDL_Scancode.SDL_SCANCODE_DOWN, Key.Down },
            { SDL_Scancode.SDL_SCANCODE_UP, Key.Up },
            { SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR, Key.NumLock },
            { SDL_Scancode.SDL_SCANCODE_KP_DIVIDE, Key.KeypadDivide },
            { SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY, Key.KeypadMultiply },
            { SDL_Scancode.SDL_SCANCODE_KP_MINUS, Key.KeypadSubtract },
            { SDL_Scancode.SDL_SCANCODE_KP_PLUS, Key.KeypadAdd },
            { SDL_Scancode.SDL_SCANCODE_KP_ENTER, Key.KeypadEnter },
            { SDL_Scancode.SDL_SCANCODE_KP_1, Key.Keypad1 },
            { SDL_Scancode.SDL_SCANCODE_KP_2, Key.Keypad2 },
            { SDL_Scancode.SDL_SCANCODE_KP_3, Key.Keypad3 },
            { SDL_Scancode.SDL_SCANCODE_KP_4, Key.Keypad4 },
            { SDL_Scancode.SDL_SCANCODE_KP_5, Key.Keypad5 },
            { SDL_Scancode.SDL_SCANCODE_KP_6, Key.Keypad6 },
            { SDL_Scancode.SDL_SCANCODE_KP_7, Key.Keypad7 },
            { SDL_Scancode.SDL_SCANCODE_KP_8, Key.Keypad8 },
            { SDL_Scancode.SDL_SCANCODE_KP_9, Key.Keypad9 },
            { SDL_Scancode.SDL_SCANCODE_KP_0, Key.Keypad0 },
            { SDL_Scancode.SDL_SCANCODE_KP_PERIOD, Key.KeypadDecimal },
            { SDL_Scancode.SDL_SCANCODE_NONUSBACKSLASH, Key.BackSlash },
            { SDL_Scancode.SDL_SCANCODE_APPLICATION, Key.Menu },
            //{SDL_Scancode.ScancodePower, /* no mapping */},
            { SDL_Scancode.SDL_SCANCODE_KP_EQUALS, Key.KeypadEqual },
            { SDL_Scancode.SDL_SCANCODE_F13, Key.F13 },
            { SDL_Scancode.SDL_SCANCODE_F14, Key.F14 },
            { SDL_Scancode.SDL_SCANCODE_F15, Key.F15 },
            { SDL_Scancode.SDL_SCANCODE_F16, Key.F16 },
            { SDL_Scancode.SDL_SCANCODE_F17, Key.F17 },
            { SDL_Scancode.SDL_SCANCODE_F18, Key.F18 },
            { SDL_Scancode.SDL_SCANCODE_F19, Key.F19 },
            { SDL_Scancode.SDL_SCANCODE_F20, Key.F20 },
            { SDL_Scancode.SDL_SCANCODE_F21, Key.F21 },
            { SDL_Scancode.SDL_SCANCODE_F22, Key.F22 },
            { SDL_Scancode.SDL_SCANCODE_F23, Key.F23 },
            { SDL_Scancode.SDL_SCANCODE_F24, Key.F24 },
            // { SDL_Scancode.ScancodeExecute, /* no mapping */ },
            // { SDL_Scancode.ScancodeHelp, /* no mapping */ },
            { SDL_Scancode.SDL_SCANCODE_MENU, Key.Menu },
            // { SDL_Scancode.ScancodeSelect, /* no mapping */ },
            // { SDL_Scancode.ScancodeStop, /* no mapping */ },
            // { SDL_Scancode.ScancodeAgain, /* no mapping */ },
            // { SDL_Scancode.ScancodeUndo, /* no mapping */ },
            // { SDL_Scancode.ScancodeCut, /* no mapping */ },
            // { SDL_Scancode.ScancodeCopy, /* no mapping */ },
            // { SDL_Scancode.ScancodePaste, /* no mapping */ },
            // { SDL_Scancode.ScancodeFind, /* no mapping */ },
            // { SDL_Scancode.ScancodeMute, /* no mapping */ },
            // { SDL_Scancode.ScancodeVolumeup, /* no mapping */ },
            // { SDL_Scancode.ScancodeVolumedown, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPComma, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPEqualsas400, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational1, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational2, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational3, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational4, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational5, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational6, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational7, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational8, /* no mapping */ },
            // { SDL_Scancode.ScancodeInternational9, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang1, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang2, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang3, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang4, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang5, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang6, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang7, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang8, /* no mapping */ },
            // { SDL_Scancode.ScancodeLang9, /* no mapping */ },
            // { SDL_Scancode.ScancodeAlterase, /* no mapping */ },
            // { SDL_Scancode.ScancodeSysreq, /* no mapping */ },
            // { SDL_Scancode.ScancodeCancel, /* no mapping */ },
            // { SDL_Scancode.ScancodeClear, /* no mapping */ },
            // { SDL_Scancode.ScancodePrior, /* no mapping */ },
            { SDL_Scancode.SDL_SCANCODE_RETURN2, Key.Enter },
            // { SDL_Scancode.ScancodeSeparator, /* no mapping */ },
            // { SDL_Scancode.ScancodeOut, /* no mapping */ },
            // { SDL_Scancode.ScancodeOper, /* no mapping */ },
            // { SDL_Scancode.ScancodeClearagain, /* no mapping */ },
            // { SDL_Scancode.ScancodeCrsel, /* no mapping */ },
            // { SDL_Scancode.ScancodeExsel, /* no mapping */ },
            // { SDL_Scancode.ScancodeKP00, /* no mapping */ },
            // { SDL_Scancode.ScancodeKP000, /* no mapping */ },
            // { SDL_Scancode.ScancodeThousandsseparator, /* no mapping */ },
            // { SDL_Scancode.ScancodeDecimalseparator, /* no mapping */ },
            // { SDL_Scancode.ScancodeCurrencyunit, /* no mapping */ },
            // { SDL_Scancode.ScancodeCurrencysubunit, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPLeftparen, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPRightparen, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPLeftbrace, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPRightbrace, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPTab, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPBackspace, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPA, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPB, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPC, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPD, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPE, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPF, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPXor, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPPower, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPPercent, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPLess, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPGreater, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPAmpersand, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPDblampersand, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPVerticalbar, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPDblverticalbar, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPColon, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPHash, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPSpace, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPAT, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPExclam, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPMemstore, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPMemrecall, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPMemclear, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPMemadd, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPMemsubtract, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPMemmultiply, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPMemdivide, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPPlusminus, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPClear, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPClearentry, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPBinary, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPOctal, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPDecimal, /* no mapping */ },
            // { SDL_Scancode.ScancodeKPHexadecimal, /* no mapping */ },
            { SDL_Scancode.SDL_SCANCODE_LCTRL, Key.ControlLeft },
            { SDL_Scancode.SDL_SCANCODE_LSHIFT, Key.ShiftLeft },
            { SDL_Scancode.SDL_SCANCODE_LALT, Key.AltLeft },
            { SDL_Scancode.SDL_SCANCODE_LGUI, Key.SuperLeft },
            { SDL_Scancode.SDL_SCANCODE_RCTRL, Key.ControlRight },
            { SDL_Scancode.SDL_SCANCODE_RSHIFT, Key.ShiftRight },
            { SDL_Scancode.SDL_SCANCODE_RALT, Key.AltRight },
            { SDL_Scancode.SDL_SCANCODE_RGUI, Key.SuperRight },
            // { SDL_Scancode.ScancodeMode, /* no mapping */ },
            // { SDL_Scancode.ScancodeAudionext, /* no mapping */ },
            // { SDL_Scancode.ScancodeAudioprev, /* no mapping */ },
            // { SDL_Scancode.ScancodeAudiostop, /* no mapping */ },
            // { SDL_Scancode.ScancodeAudioplay, /* no mapping */ },
            // { SDL_Scancode.ScancodeAudiomute, /* no mapping */ },
            // { SDL_Scancode.ScancodeMediaselect, /* no mapping */ },
            // { SDL_Scancode.ScancodeWww, /* no mapping */ },
            // { SDL_Scancode.ScancodeMail, /* no mapping */ },
            // { SDL_Scancode.ScancodeCalculator, /* no mapping */ },
            // { SDL_Scancode.ScancodeComputer, /* no mapping */ },
            // { SDL_Scancode.ScancodeACSearch, /* no mapping */ },
            // { SDL_Scancode.ScancodeACHome, /* no mapping */ },
            // { SDL_Scancode.ScancodeACBack, /* no mapping */ },
            // { SDL_Scancode.ScancodeACForward, /* no mapping */ },
            // { SDL_Scancode.ScancodeACStop, /* no mapping */ },
            // { SDL_Scancode.ScancodeACRefresh, /* no mapping */ },
            // { SDL_Scancode.ScancodeACBookmarks, /* no mapping */ },
            // { SDL_Scancode.ScancodeBrightnessdown, /* no mapping */ },
            // { SDL_Scancode.ScancodeBrightnessup, /* no mapping */ },
            // { SDL_Scancode.ScancodeDisplayswitch, /* no mapping */ },
            // { SDL_Scancode.ScancodeKbdillumtoggle, /* no mapping */ },
            // { SDL_Scancode.ScancodeKbdillumdown, /* no mapping */ },
            // { SDL_Scancode.ScancodeKbdillumup, /* no mapping */ },
            // { SDL_Scancode.ScancodeEject, /* no mapping */ },
            // { SDL_Scancode.ScancodeSleep, /* no mapping */ },
            // { SDL_Scancode.ScancodeApp1, /* no mapping */ },
            // { SDL_Scancode.ScancodeApp2, /* no mapping */ },
            // { SDL_Scancode.ScancodeAudiorewind, /* no mapping */ },
            // { SDL_Scancode.ScancodeAudiofastforward, /* no mapping */ },
        };
    }
}
